CREATE TABLE IF NOT EXISTS pedidos (
    id SERIAL PRIMARY KEY,

    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE_PAGO',

    total NUMERIC(12, 2) NOT NULL DEFAULT 0,

    pago_confirmado BOOLEAN NOT NULL DEFAULT FALSE,

    codigo_confirmacion VARCHAR(20) UNIQUE,

    codigo_usado BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);